services:
  web:
    image: ghcr.io/technospartan/ft-rc-bko-trucksworks:staging-latest
    container_name: cyberdyne-staging
    restart: unless-stopped
    ports:
      - "8081:80"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--show-error", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - traefik.enable=true
      - traefik.http.routers.cyberdyne-staging.rule=Host(`staging.cyberdyne-systems.es`)
      - traefik.http.routers.cyberdyne-staging.entrypoints=websecure
      - traefik.http.routers.cyberdyne-staging.tls=true
      - traefik.http.routers.cyberdyne-staging.tls.certresolver=le
      - traefik.http.services.cyberdyne-staging.loadbalancer.server.port=80
      - traefik.docker.network=web

    networks:
      - web

networks:
  web:
    external: true
