version: '3.8'

services:
  frontend:
    image: ghcr.io/technospartan/ft-rc-bko-dummy:latest
    container_name: cyberdyne-frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.cyberdyne-frontend.rule=Host(`www.cyberdyne-systems.es`)
      - traefik.http.routers.cyberdyne-frontend.entrypoints=websecure
      - traefik.http.routers.cyberdyne-frontend.tls=true
      - traefik.http.routers.cyberdyne-frontend.tls.certresolver=le
      - traefik.docker.network=web
      - traefik.http.services.cyberdyne-frontend.loadbalancer.server.port=80

    networks:
      - web

networks:
  web:
    external: true
