name: Deploy Backoffice

on:
  workflow_dispatch:
  push:
    paths:
      - 'codespartan/platform/stacks/backoffice/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare files
        run: |
          mkdir -p artifacts/backoffice
          cp -r codespartan/platform/stacks/backoffice/* artifacts/backoffice/

      - name: Prepare remote dir
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /opt/codespartan/platform/stacks/backoffice

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "artifacts/backoffice/*"
          target: "/opt/codespartan/platform/stacks/backoffice"
          strip_components: 2

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -euxo pipefail
            docker network create web || true
            cd /opt/codespartan/platform/stacks/backoffice
            docker compose pull
            docker compose up -d
