name: Deploy Backup System

on:
  push:
    branches: [main]
    paths:
      - 'codespartan/platform/stacks/backups/**'
      - '.github/workflows/deploy-backup-system.yml'
  workflow_dispatch:

jobs:
  deploy-backup-system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create backup scripts directory on VPS
        run: |
          ssh ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }} "mkdir -p /opt/codespartan/platform/stacks/backups"

      - name: Deploy backup scripts
        run: |
          scp codespartan/platform/stacks/backups/backup.sh \
            ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }}:/opt/codespartan/platform/stacks/backups/backup.sh

          scp codespartan/platform/stacks/backups/restore.sh \
            ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }}:/opt/codespartan/platform/stacks/backups/restore.sh

          scp codespartan/platform/stacks/backups/setup-cron.sh \
            ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }}:/opt/codespartan/platform/stacks/backups/setup-cron.sh

      - name: Set script permissions and create directories
        run: |
          ssh ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }} << 'EOF'
            chmod +x /opt/codespartan/platform/stacks/backups/backup.sh
            chmod +x /opt/codespartan/platform/stacks/backups/restore.sh
            chmod +x /opt/codespartan/platform/stacks/backups/setup-cron.sh
            mkdir -p /opt/backups
            echo "✅ Scripts deployed and made executable"
            echo "✅ Backup directory created at /opt/backups"
          EOF

      - name: Configure cron job for weekly backups
        run: |
          ssh ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }} << 'EOF'
            # Remove existing backup cron job if it exists
            crontab -l 2>/dev/null | grep -v 'backup.sh' | crontab - || true

            # Add new cron job (weekly on Sundays at 2:00 AM)
            (crontab -l 2>/dev/null; echo "0 2 * * 0 /opt/codespartan/platform/stacks/backups/backup.sh >> /var/log/codespartan-backup.log 2>&1") | crontab -

            echo "✅ Cron job configured: Weekly backups on Sundays at 2:00 AM"
            echo ""
            echo "Current crontab:"
            crontab -l
          EOF

      - name: Create initial backup
        run: |
          ssh ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }} << 'EOF'
            echo "Creating initial backup..."

            # Run backup script
            /opt/codespartan/platform/stacks/backups/backup.sh

            # List created backups
            echo ""
            echo "Backups created:"
            ls -lh /opt/backups/

            # Show backup info
            if ls /opt/backups/backup_*.tar.gz 1> /dev/null 2>&1; then
              latest_backup=$(ls -t /opt/backups/backup_*.tar.gz | head -1)
              echo ""
              echo "Latest backup details:"
              echo "  File: ${latest_backup}"
              echo "  Size: $(du -h ${latest_backup} | cut -f1)"
            fi
          EOF

      - name: Cleanup SSH key
        if: always()
        run: rm -f ~/.ssh/id_rsa

      - name: Deployment summary
        run: |
          echo "✅ Backup system deployed successfully!"
          echo ""
          echo "📋 Summary:"
          echo "  - backup.sh: /opt/codespartan/platform/stacks/backups/backup.sh"
          echo "  - restore.sh: /opt/codespartan/platform/stacks/backups/restore.sh"
          echo "  - setup-cron.sh: /opt/codespartan/platform/stacks/backups/setup-cron.sh"
          echo "  - Backup dir: /opt/backups/"
          echo "  - Cron schedule: Weekly on Sundays at 2:00 AM"
          echo "  - Retention: Last 7 backups"
          echo ""
          echo "📦 What gets backed up:"
          echo "  - Grafana dashboards and datasources"
          echo "  - VictoriaMetrics data snapshots"
          echo "  - Loki configuration"
          echo "  - Traefik SSL certificates (acme.json)"
          echo "  - All configuration files (docker-compose.yml, .env, etc)"
          echo ""
          echo "📚 Commands:"
          echo "  - Manual backup: ssh leonidas@91.98.137.217 'sudo /opt/codespartan/platform/stacks/backups/backup.sh'"
          echo "  - List backups: ssh leonidas@91.98.137.217 'ls -lh /opt/backups/'"
          echo "  - Restore backup: ssh leonidas@91.98.137.217 'sudo /opt/codespartan/platform/stacks/backups/restore.sh /opt/backups/backup_YYYYMMDD_HHMMSS.tar.gz'"
          echo "  - View logs: ssh leonidas@91.98.137.217 'tail -f /var/log/codespartan-backup.log'"
