name: Deploy Backups (Restic)

on:
  workflow_dispatch:
  push:
    paths:
      - 'codespartan/platform/stacks/backups/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy backups stack
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "codespartan/platform/stacks/backups/*"
          target: "/opt/codespartan/platform/stacks/backups/"
          strip_components: 4

      - name: Deploy backups
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euo pipefail
            mkdir -p /opt/codespartan/platform/stacks/backups
            cat > /opt/codespartan/platform/stacks/backups/.env <<EOF
            BACKUP_CRON=${{ secrets.BACKUP_CRON }}
            RESTIC_REPOSITORY=${{ secrets.RESTIC_REPOSITORY }}
            RESTIC_PASSWORD=${{ secrets.RESTIC_PASSWORD }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
            EOF
            cd /opt/codespartan/platform/stacks/backups
            docker compose --env-file .env up -d
version: '3.8'
services:
  restic-backup:
    image: lobaro/restic-backup-docker:1.4.0
    container_name: restic-backup
    environment:
      - TZ=Europe/Madrid
      - BACKUP_CRON=${BACKUP_CRON}
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - RESTIC_BACKUP_SOURCES=/data
      - RESTIC_BACKUP_ARGS=--verbose
      - RESTIC_FORGET_ARGS=--keep-daily 7 --keep-weekly 4 --keep-monthly 6
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - /opt/codespartan:/data:ro
    restart: unless-stopped

