
services:
  app:
    # Replace with your application image (e.g., node:18-alpine, python:3.11-slim, nginx:alpine)
    image: nginx:alpine
    container_name: ${APP_NAME:-myapp}-app

    # Traefik labels for automatic routing and SSL
    labels:
      - traefik.enable=true

      # Main router configuration
      - traefik.http.routers.${APP_NAME:-myapp}.rule=Host(`${SUBDOMAIN:-app}.mambo-cloud.com`)
      - traefik.http.routers.${APP_NAME:-myapp}.entrypoints=websecure
      - traefik.http.routers.${APP_NAME:-myapp}.tls=true
      - traefik.http.routers.${APP_NAME:-myapp}.tls.certresolver=le
      - traefik.docker.network=web

      # Service configuration
      - traefik.http.services.${APP_NAME:-myapp}.loadbalancer.server.port=${APP_PORT:-80}

      # Optional: Add middlewares (uncomment to enable)
      # Available middlewares from dynamic-config.yml:
      # - rate-limit-global@file (100 req/s)
      # - rate-limit-strict@file (10 req/s)
      # - rate-limit-api@file (50 req/s)
      # - security-headers@file (security headers)
      # - compression@file (gzip compression)
      # - cors-api@file (CORS for APIs)

      # Example: Enable rate limiting + security headers + compression
      # - traefik.http.routers.${APP_NAME:-myapp}.middlewares=rate-limit-global@file,security-headers@file,compression@file

      # Optional: Add basic auth (define middleware inline)
      # - traefik.http.routers.${APP_NAME:-myapp}.middlewares=auth
      # - traefik.http.middlewares.auth.basicauth.users=${BASIC_AUTH_USERS}

    # Environment variables
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - APP_PORT=${APP_PORT:-80}
      # Add your app-specific environment variables here

    # Optional: Add env_file for sensitive variables
    # env_file:
    #   - .env

    # Volumes (uncomment and customize as needed)
    # volumes:
    #   - ./data:/app/data
    #   - ./config:/app/config:ro

    # Networks
    networks:
      - web     # Required: For Traefik to route traffic
      - backend # Optional: For internal communication with database/cache

    # Health check (customize according to your app)
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${APP_PORT:-80}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Restart policy
    restart: unless-stopped

    # Resource limits (uncomment to enable)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 128M

  # Optional: Database service (PostgreSQL example)
  # Uncomment to add a database to your application
  #
  # database:
  #   image: postgres:15-alpine  # ARM64 compatible
  #   container_name: ${APP_NAME:-myapp}-db
  #   environment:
  #     - POSTGRES_USER=${DB_USER:-appuser}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME:-appdb}
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   networks:
  #     - backend  # ONLY backend network - NOT accessible from internet
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-appuser}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #
  # Optional: Redis cache example
  #
  # redis:
  #   image: redis:7-alpine  # ARM64 compatible
  #   container_name: ${APP_NAME:-myapp}-redis
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - backend  # ONLY backend network - NOT accessible from internet
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  # External network (managed by Traefik)
  web:
    external: true

  # Internal network for inter-service communication
  backend:
    name: ${APP_NAME:-myapp}_internal
    driver: bridge
    internal: true  # No internet access - maximum security for databases
    ipam:
      config:
        - subnet: 172.23.0.0/24

# Persistent volumes for databases
# volumes:
#   db-data:
#     name: ${APP_NAME:-myapp}_postgres_data
#   redis-data:
#     name: ${APP_NAME:-myapp}_redis_data
